### ISSUE TITLE
Show a warning if in multi-threaded mode and the datastorage is sqlite

### ISSUE THREAD

**Issue by uhhhuh** [alephdata/memorious#48]
ERROR:tj_procurement.store_record:(sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139692792108800 and this is thread id 139692800501504 (Background on this error at: http://sqlalche.me/e/f405)
Traceback (most recent call last):
  File "/home/memorious/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/memorious/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 637, in _init_compiled
    self.cursor = self.create_cursor()
  File "/home/memorious/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 952, in create_cursor
    return self._dbapi_connection.cursor()
  File "/home/memorious/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 977, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139692792108800 and this is thread id 139692800501504

Fixed with `export MEMORIOUS_DEBUG=true'

**Comment by naomifox-invitae** [comment]
I ran into the same issue today when using UTA with Seqrepo in a flask application.  Creating the uta data provider object (returned by `uta.connect('connection-string')`) within the function called by the thread, rather than globally, is the not great work-around I came up with.

**Comment by sunu** [comment]
We now show a warning when memorious is run in multi-threaded mode with sqlite as the datastore
