### ISSUE TITLE
Running a scraper in the example fails with an error when calling context.set_tag(tag, None)

### ISSUE THREAD

**Issue by alexmojaki** [alephdata/memorious#72]
I ran `docker-compose up` and was able to view the UI. However, if I run any of the three crawlers I get an error like this:

```
worker_1  | INFO:book_scraper.init:[book_scraper->init(seed)]: b7feff0ca24511e9af6f0242ac130003
worker_1  | INFO:book_scraper.fetch:[book_scraper->fetch(fetch)]: b7feff0ca24511e9af6f0242ac130003
worker_1  | INFO:book_scraper.fetch:Using cached HTTP response: http://books.toscrape.com/
worker_1  | INFO:book_scraper.fetch:Fetched [200]: 'http://books.toscrape.com/'
worker_1  | ERROR:book_scraper.fetch:Invalid input of type: 'NoneType'. Convert to a byte, string or number first.
worker_1  | Traceback (most recent call last):
worker_1  |   File "/memorious/memorious/logic/context.py", line 75, in execute
worker_1  |     return self.stage.method(self, data)
worker_1  |   File "/memorious/memorious/operations/fetch.py", line 32, in fetch
worker_1  |     context.set_tag(tag, None)
worker_1  |   File "/memorious/memorious/logic/context.py", line 105, in set_tag
worker_1  |     return conn.set(key, data, ex=self.crawler.expire)
worker_1  |   File "/usr/lib/python3.7/site-packages/redis/client.py", line 1451, in set
worker_1  |     return self.execute_command('SET', *pieces)
worker_1  |   File "/usr/lib/python3.7/site-packages/redis/client.py", line 774, in execute_command
worker_1  |     connection.send_command(*args)
worker_1  |   File "/usr/lib/python3.7/site-packages/redis/connection.py", line 620, in send_command
worker_1  |     self.send_packed_command(self.pack_command(*args))
worker_1  |   File "/usr/lib/python3.7/site-packages/redis/connection.py", line 663, in pack_command
worker_1  |     for arg in imap(self.encoder.encode, args):
worker_1  |   File "/usr/lib/python3.7/site-packages/redis/connection.py", line 125, in encode
worker_1  |     "byte, string or number first." % typename)
worker_1  | redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a byte, string or number first.
```

This happens from both the UI and when I ran the command:

    docker-compose exec worker memorious run book_scraper

The quote scrapers shows the above error as well as this:

```
worker_1  | INFO:memorious.logic.crawler:Running aggregator for quote_scraper
worker_1  | ERROR:memorious.task_runner:Task failed to execute:
worker_1  | Traceback (most recent call last):
worker_1  |   File "/memorious/memorious/task_runner.py", line 59, in process
worker_1  |     cls.execute(*item)
worker_1  |   File "/memorious/memorious/task_runner.py", line 49, in execute
worker_1  |     context.crawler.aggregate(context)
worker_1  |   File "/memorious/memorious/logic/crawler.py", line 80, in aggregate
worker_1  |     context, self.aggregator_config.get("params", {})
worker_1  |   File "/crawlers/src/example/quotes.py", line 71, in export
worker_1  |     table = context.datastore[context.params.get("table")]
worker_1  |   File "/usr/lib/python3.7/site-packages/werkzeug/local.py", line 378, in <lambda>
worker_1  |     __getitem__ = lambda x, i: x._get_current_object()[i]
worker_1  |   File "/usr/lib/python3.7/site-packages/dataset/database.py", line 222, in __getitem__
worker_1  |     return self.get_table(table_name)
worker_1  |   File "/usr/lib/python3.7/site-packages/dataset/database.py", line 218, in get_table
worker_1  |     return self.create_table(table_name, primary_id, primary_type)
worker_1  |   File "/usr/lib/python3.7/site-packages/dataset/database.py", line 181, in create_table
worker_1  |     table_name = normalize_table_name(table_name)
worker_1  |   File "/usr/lib/python3.7/site-packages/dataset/util.py", line 79, in normalize_table_name
worker_1  |     raise ValueError("Invalid table name: %r" % name)
worker_1  | ValueError: Invalid table name: None
```

**Comment by sunu** [comment]
Can you try the current master? Ideally this should be fixed. Please let me know if it's not.

**Comment by alexmojaki** [comment]
I pulled master, built with no cache, composed up, and got this:

```
beat_1            | Traceback (most recent call last):
beat_1            |   File "/usr/bin/memorious", line 11, in <module>
beat_1            |     load_entry_point('memorious', 'console_scripts', 'memorious')()
beat_1            |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
beat_1            |     return get_distribution(dist).load_entry_point(group, name)
beat_1            |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
beat_1            |     return ep.load()
beat_1            |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
beat_1            |     return self.resolve()
beat_1            |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
beat_1            |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
beat_1            |   File "/memorious/memorious/cli.py", line 8, in <module>
beat_1            |     from memorious.model import Queue
beat_1            |   File "/memorious/memorious/model/__init__.py", line 1, in <module>
beat_1            |     from memorious.model.event import Event  # noqa
beat_1            |   File "/memorious/memorious/model/event.py", line 3, in <module>
beat_1            |     from servicelayer.util import pack_now, unpack_datetime
beat_1            | ImportError: cannot import name 'pack_now' from 'servicelayer.util' (/usr/lib/python3.7/site-packages/servicelayer/util.py)
example_beat_1 exited with code 1
```

**Comment by sunu** [comment]
Can you do a `docker-compose build` too? That should pull in the latest memorious image which has servicelayer >= 1.5.0 installed.

**Comment by alexmojaki** [comment]
OK, the services can run again, but there's a new error when crawling:

```
➜  example git:(master) docker pull alephdata/memorious:latest       
latest: Pulling from alephdata/memorious
Digest: sha256:474904e69d089932bf6e2b5cf8f4a2dbd0bf84b8ccc618d3fd21c326884b805a
Status: Image is up to date for alephdata/memorious:latest
➜  example git:(master) git checkout master && git pull origin master
Already on 'master'
Your branch is up to date with 'origin/master'.
From github.com:alephdata/memorious
 * branch            master     -> FETCH_HEAD
Already up to date.
➜  example git:(master) pwd                                          
/home/alex/work/memorious/example
➜  example git:(master) docker-compose build --no-cache              
redis uses an image, skipping
recognize-text uses an image, skipping
Building beat
Step 1/6 : FROM alephdata/memorious:latest
 ---> 2bb095303e73
Step 2/6 : COPY setup.py /crawlers/
 ---> e1be0998f19d
Step 3/6 : COPY src /crawlers/src
 ---> baec80b38994
Step 4/6 : RUN pip3 install -q -e /crawlers
 ---> Running in e1eaddd3bcca
Removing intermediate container e1eaddd3bcca
 ---> d4123c725e79
Step 5/6 : COPY config /crawlers/config
 ---> 5a1eab38315c
Step 6/6 : ENV MEMORIOUS_CONFIG_PATH=/crawlers/config     MEMORIOUS_BASE_PATH=/data     MEMORIOUS_DEBUG=false     REDIS_URL=redis://redis:6379/0     ARCHIVE_PATH=archive
 ---> Running in ac2eb6b66f92
Removing intermediate container ac2eb6b66f92
 ---> c9de1b7a4e59
Successfully built c9de1b7a4e59
Successfully tagged example_beat:latest
Building ui
Step 1/6 : FROM alephdata/memorious:latest
 ---> 2bb095303e73
Step 2/6 : COPY setup.py /crawlers/
 ---> 7efe55cb7b14
Step 3/6 : COPY src /crawlers/src
 ---> fe615b2db429
Step 4/6 : RUN pip3 install -q -e /crawlers
 ---> Running in c1285ae936a5
Removing intermediate container c1285ae936a5
 ---> 0a1af002b887
Step 5/6 : COPY config /crawlers/config
 ---> 3bb1e1c0b44d
Step 6/6 : ENV MEMORIOUS_CONFIG_PATH=/crawlers/config     MEMORIOUS_BASE_PATH=/data     MEMORIOUS_DEBUG=false     REDIS_URL=redis://redis:6379/0     ARCHIVE_PATH=archive
 ---> Running in 17da36201ac3
Removing intermediate container 17da36201ac3
 ---> 8c57e6ccc839
Successfully built 8c57e6ccc839
Successfully tagged example_ui:latest
Building worker
Step 1/6 : FROM alephdata/memorious:latest
 ---> 2bb095303e73
Step 2/6 : COPY setup.py /crawlers/
 ---> 051e6958d724
Step 3/6 : COPY src /crawlers/src
 ---> 08e14713b736
Step 4/6 : RUN pip3 install -q -e /crawlers
 ---> Running in 876a53e48fd4
Removing intermediate container 876a53e48fd4
 ---> 6511e164138a
Step 5/6 : COPY config /crawlers/config
 ---> 9f180a81ddd9
Step 6/6 : ENV MEMORIOUS_CONFIG_PATH=/crawlers/config     MEMORIOUS_BASE_PATH=/data     MEMORIOUS_DEBUG=false     REDIS_URL=redis://redis:6379/0     ARCHIVE_PATH=archive
 ---> Running in d76dbe04c26f
Removing intermediate container d76dbe04c26f
 ---> 699ee9fe8aaa
Successfully built 699ee9fe8aaa
Successfully tagged example_worker:latest
Building shell
Step 1/6 : FROM alephdata/memorious:latest
 ---> 2bb095303e73
Step 2/6 : COPY setup.py /crawlers/
 ---> 43d2ffcbd6cc
Step 3/6 : COPY src /crawlers/src
 ---> a37144c27ef0
Step 4/6 : RUN pip3 install -q -e /crawlers
 ---> Running in cf43d067fab6
Removing intermediate container cf43d067fab6
 ---> 1012355680d6
Step 5/6 : COPY config /crawlers/config
 ---> 004343dba915
Step 6/6 : ENV MEMORIOUS_CONFIG_PATH=/crawlers/config     MEMORIOUS_BASE_PATH=/data     MEMORIOUS_DEBUG=false     REDIS_URL=redis://redis:6379/0     ARCHIVE_PATH=archive
 ---> Running in 1dffa9ccca92
Removing intermediate container 1dffa9ccca92
 ---> ceaba52095cb
Successfully built ceaba52095cb
Successfully tagged example_shell:latest
➜  example git:(master) docker-compose up              
Starting example_recognize-text_1 ... done
Starting example_redis_1          ... done
Recreating example_worker_1       ... done
Recreating example_beat_1         ... done
Recreating example_shell_1        ... done
Recreating example_ui_1           ... done
Attaching to example_redis_1, example_recognize-text_1, example_shell_1, example_beat_1, example_worker_1, example_ui_1
redis_1           | 1:C 11 Jul 2019 15:05:57.827 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 11 Jul 2019 15:05:57.827 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 11 Jul 2019 15:05:57.827 # Configuration loaded
redis_1           | 1:M 11 Jul 2019 15:05:57.829 * Running mode=standalone, port=6379.
redis_1           | 1:M 11 Jul 2019 15:05:57.829 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1           | 1:M 11 Jul 2019 15:05:57.829 # Server initialized
beat_1            | INFO:memorious.logic.manager:Checking schedule: 3 crawlers.
recognize-text_1  | INFO:service:Server started: [::]:50000
redis_1           | 1:M 11 Jul 2019 15:05:57.829 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
beat_1            | INFO:memorious.logic.manager:Checking schedule: 3 crawlers.
example_shell_1 exited with code 0
redis_1           | 1:M 11 Jul 2019 15:05:57.829 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1           | 1:M 11 Jul 2019 15:05:57.831 * DB loaded from append only file: 0.002 seconds
redis_1           | 1:M 11 Jul 2019 15:05:57.831 * Ready to accept connections
worker_1          | INFO:memorious.task_runner:Processing queue (8 threads)
ui_1              | [2019-07-11 15:06:04 +0000] [1] [INFO] Starting gunicorn 19.7.1
ui_1              | [2019-07-11 15:06:04 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
ui_1              | [2019-07-11 15:06:04 +0000] [1] [INFO] Using worker: sync
ui_1              | [2019-07-11 15:06:04 +0000] [7] [INFO] Booting worker with pid: 7
ui_1              | [2019-07-11 15:06:04 +0000] [8] [INFO] Booting worker with pid: 8
ui_1              | [2019-07-11 15:06:04 +0000] [9] [INFO] Booting worker with pid: 9
ui_1              | [2019-07-11 15:06:04 +0000] [10] [INFO] Booting worker with pid: 10
ui_1              | [2019-07-11 15:06:04 +0000] [11] [INFO] Booting worker with pid: 11
ui_1              | [2019-07-11 15:06:04 +0000] [12] [INFO] Booting worker with pid: 12
ui_1              | [2019-07-11 15:06:04 +0000] [13] [INFO] Booting worker with pid: 13
ui_1              | [2019-07-11 15:06:04 +0000] [14] [INFO] Booting worker with pid: 14
beat_1            | INFO:memorious.logic.manager:Checking schedule: 3 crawlers.
beat_1            | INFO:memorious.logic.manager:Checking schedule: 3 crawlers.
beat_1            | INFO:memorious.logic.manager:Checking schedule: 3 crawlers.
worker_1          | INFO:book_scraper.init:[book_scraper->init(seed)]: e09a77f8a3ed11e9aead0242ac130006
worker_1          | INFO:book_scraper.fetch:[book_scraper->fetch(fetch)]: e09a77f8a3ed11e9aead0242ac130006
worker_1          | INFO:book_scraper.fetch:Using cached HTTP response: http://books.toscrape.com/
worker_1          | INFO:book_scraper.fetch:Fetched [200]: 'http://books.toscrape.com/'
worker_1          | INFO:book_scraper.parse:[book_scraper->parse(parse)]: e09a77f8a3ed11e9aead0242ac130006
worker_1          | ERROR:book_scraper.parse:expected str, bytes or os.PathLike object, not NoneType
worker_1          | Traceback (most recent call last):
worker_1          |   File "/memorious/memorious/logic/context.py", line 76, in execute
worker_1          |     return self.stage.method(self, data)
worker_1          |   File "/memorious/memorious/operations/parse.py", line 91, in parse
worker_1          |     if result.html is not None:
worker_1          |   File "/memorious/memorious/logic/http.py", line 310, in html
worker_1          |     if self.raw is None or not len(self.raw):
worker_1          |   File "/memorious/memorious/logic/http.py", line 293, in raw
worker_1          |     if self.file_path is not None:
worker_1          |   File "/memorious/memorious/logic/http.py", line 261, in file_path
worker_1          |     return Path(self._file_path)
worker_1          |   File "/usr/lib/python3.7/pathlib.py", line 1003, in __new__
worker_1          |     self = cls._from_parts(args, init=False)
worker_1          |   File "/usr/lib/python3.7/pathlib.py", line 658, in _from_parts
worker_1          |     drv, root, parts = self._parse_args(args)
worker_1          |   File "/usr/lib/python3.7/pathlib.py", line 642, in _parse_args
worker_1          |     a = os.fspath(a)
worker_1          | TypeError: expected str, bytes or os.PathLike object, not NoneType
beat_1            | INFO:memorious.logic.manager:Checking schedule: 3 crawlers.
```

**Comment by sunu** [comment]
Should be fixed now.
